# **Classification** des **séries temporelles** avec `sktime`

## Métadonnées

- **Expérience nº :** 2.2.1
- **Date :** 09/11/2023
- **Heure :** 14:38
- **Données :** `ready_Evaporation_Sunshine.csv`
- **Tri :** par défaut
- **Découpage :** `TimeSeriesSplit`
- **Mise à l'échelle :** non
- **Rééquilibrage :** non
- **Conversion :** `numpyfy`
- **Algorithme :** TSF

## Sommaire

1. Initialisation
2. Découpage
3. Conversion
4. Modélisation
5. Évaluation

## 1. Initialisation

In [1]:
# Importation des bibliothèques et modules nécessaires au fonctionnement de ce notebook

import pandas as pd
import numpy as np

from sklearn.metrics import classification_report

In [2]:
# Importation du jeu de données et enregistrement dans le DataFrame `df`

df = pd.read_csv("../../../../data/processed/omar/ready_Evaporation_Sunshine.csv", index_col = 1)
df = df.drop(columns = "Unnamed: 0")

In [3]:
# Inspection de la structure de `df`

df.head()

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  \
Date                                                                  
2008-12-01     13.4     22.9       0.6           44.0          20.0   
2008-12-02      7.4     25.1       0.0           44.0           4.0   
2008-12-03     12.9     25.7       0.0           46.0          19.0   
2008-12-04      9.2     28.0       0.0           24.0          11.0   
2008-12-05     17.5     32.3       1.0           41.0           7.0   

            WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  \
Date                                                                           
2008-12-01          24.0         71.0         22.0       1007.7       1007.1   
2008-12-02          22.0         44.0         25.0       1010.6       1007.8   
2008-12-03          26.0         38.0         30.0       1007.6       1008.7   
2008-12-04           9.0         45.0         16.0       1017.6       1012.8   
2008-12-05          20.0         82.0         33.0       1010.8       1006.0   

            ...  year  month  day  LocationNum  WindGustDirNum  WindDir9amNum  \
Date        ...                                                                 
2008-12-01  ...  2008     12    1            0        3.141593       3.141593   
2008-12-02  ...  2008     12    2            0        2.748894       1.963495   
2008-12-03  ...  2008     12    3            0        3.534292       3.141593   
2008-12-04  ...  2008     12    4            0        0.785398       5.497787   
2008-12-05  ...  2008     12    5            0        3.141593       0.392699   

            WindDir3pmNum   Latitude  Longitude  CodeRegionNum  
Date                                                            
2008-12-01       2.748894 -36.080477  146.91628              0  
2008-12-02       3.534292 -36.080477  146.91628              0  
2008-12-03       3.534292 -36.080477  146.91628              0  
2008-12-04       0.000000 -36.080477  146.91628              0  
2008-12-05       2.356194 -36.080477  146.91628              0  

[5 rows x 26 columns]

In [4]:
# Inspection de la structure de `df`

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10453 entries, 2008-12-01 to 2017-06-24
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   MinTemp         10453 non-null  float64
 1   MaxTemp         10453 non-null  float64
 2   Rainfall        10453 non-null  float64
 3   WindGustSpeed   10453 non-null  float64
 4   WindSpeed9am    10453 non-null  float64
 5   WindSpeed3pm    10453 non-null  float64
 6   Humidity9am     10453 non-null  float64
 7   Humidity3pm     10453 non-null  float64
 8   Pressure9am     10453 non-null  float64
 9   Pressure3pm     10453 non-null  float64
 10  Cloud9am        10453 non-null  float64
 11  Cloud3pm        10453 non-null  float64
 12  Temp9am         10453 non-null  float64
 13  Temp3pm         10453 non-null  float64
 14  RainToday       10453 non-null  int64  
 15  RainTomorrow    10453 non-null  int64  
 16  year            10453 non-null  int64  
 17  month           10453 

## 2. Découpage

In [5]:
# Découpage de `df` sur l'axe des colonnes : séparation des variables explicatives (`data`) et cible (`target`)

data = df.drop(columns = "RainTomorrow")
target = df["RainTomorrow"]

In [6]:
# Découpage de `data` et de `target` sur l'axe des lignes : séparation des jeux d'entraînement (`*_train`) et de test (`*_test`) avec le splitter `TimeSeriesSplit`

from sklearn.model_selection import TimeSeriesSplit

tss = TimeSeriesSplit(n_splits = 5) ## Nous fixons le paramètre `n_splits` à 5 afin d'avoir une répartition de 80 / 20 entre les jeux d'entraînement et de test, respectivement.

for train_index, test_index in tss.split(data):
    X_train, X_test = data.iloc[train_index, :], data.iloc[test_index,:]
    y_train, y_test = target.iloc[train_index], target.iloc[test_index]

## 3. Conversion

In [7]:
# Importation de la fonction artisanale `numpyfy`

from numpyfy import numpyfy

In [8]:
# Application de la fonction `numpyfy` aux 4 jeux de données issus du découpage effectué par le splitter `TimeSeriesSplit` afin de les convertir en arrays et ainsi les rendre compatibles avec `sktime`

X_train, X_test, y_train, y_test = numpyfy(X_train, X_test, y_train, y_test)

## 4. Modélisation

In [9]:
# Instanciation d'un modèle classificateur via un Pipeline

from sklearn.pipeline import Pipeline
from sktime.transformations.panel.compose import ColumnConcatenator
from sktime.classification.interval_based import TimeSeriesForestClassifier

steps = [
    ("concatenate", ColumnConcatenator()), ## Cette étape permet de transformer les jeux de données multivariées en univariées afin qu'ils puissent être traités par `TimeSeriesForestClassifier`.
    ("classify", TimeSeriesForestClassifier()),
]

clf_rf_ts = Pipeline(steps)

In [10]:
# Récupération des paramètres initiaux de la TSF

clf_rf_ts["classify"].get_params()

{'min_interval': 3, 'n_estimators': 200, 'n_jobs': 1, 'random_state': None}

In [11]:
# Entraînement du modèle

clf_rf_ts.fit(X_train, y_train)

Pipeline(steps=[('concatenate', ColumnConcatenator()),
                ('classify', TimeSeriesForestClassifier())])

In [12]:
# Récupération des paramètres ajustés de la TSF

clf_rf_ts["classify"].get_fitted_params()

{'classes': array([0, 1]),
 'intervals': [array([[12, 23],
         [10, 18],
         [ 1, 13],
         [ 7, 20],
         [ 5,  8]]),
  array([[10, 19],
         [ 1, 17],
         [18, 23],
         [17, 23],
         [ 1,  4]]),
  array([[11, 14],
         [ 1,  6],
         [11, 18],
         [ 4, 18],
         [14, 17]]),
  array([[ 4, 18],
         [12, 15],
         [ 6, 23],
         [ 1, 13],
         [19, 23]]),
  array([[ 2, 19],
         [ 9, 12],
         [ 6, 19],
         [12, 22],
         [16, 19]]),
  array([[ 5,  8],
         [ 8, 22],
         [ 3,  9],
         [18, 23],
         [ 3, 11]]),
  array([[ 7, 20],
         [21, 24],
         [15, 23],
         [ 3, 19],
         [12, 20]]),
  array([[20, 23],
         [ 3, 19],
         [ 3,  6],
         [12, 15],
         [ 5, 23]]),
  array([[ 9, 22],
         [17, 22],
         [ 2, 18],
         [17, 20],
         [ 6, 13]]),
  array([[ 4, 19],
         [11, 17],
         [ 1, 18],
         [11, 18],
         [1

In [13]:
# Réalisation des prédictions

y_pred = clf_rf_ts.predict(X_test)

## 5. Évaluation

In [14]:
# Élaboration de la matrice de confusion

pd.crosstab(y_test, y_pred, rownames = ["Classe réelle"], colnames = ["Classe prédite"])

Classe prédite     0   1
Classe réelle           
0               1574   9
1                138  21

In [15]:
# Élaboration du rapport de classification

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96      1583
           1       0.70      0.13      0.22       159

    accuracy                           0.92      1742
   macro avg       0.81      0.56      0.59      1742
weighted avg       0.90      0.92      0.89      1742

