# **Classification** des **séries temporelles** avec `sktime`

## Métadonnées

- **Expérience nº :** 6.2.2
- **Date :** 11/11/2023
- **Heure :** 12:24
- **Données :** `ready_Evaporation_Sunshine_WindGustDir_WindGustSpeed_Pressure9am_Pressure3pm_WindGustDirNum.csv`
- **Tri :** index chronologique
- **Découpage :** `TimeSeriesSplit`
- **Mise à l'échelle :** non
- **Rééquilibrage :** non
- **Conversion :** `numpyfy`
- **Algorithme :** TSF

## Sommaire

1. Initialisation
2. Découpage
3. Conversion
4. Modélisation
5. Évaluation

## 1. Initialisation

In [1]:
# Importation des bibliothèques et modules nécessaires au fonctionnement de ce notebook

import pandas as pd
import numpy as np

from sklearn.metrics import classification_report

In [2]:
# Importation du jeu de données et enregistrement dans le DataFrame `df`

df = pd.read_csv("../../../data/9df/Alex/ready_Evaporation_Sunshine_WindGustDir_WindGustSpeed_Pressure9am_Pressure3pm_WindGustDirNum.csv", index_col = 1).sort_index()
df = df.drop(columns = "Unnamed: 0")

In [3]:
# Inspection de la structure de `df`

df.head()

MinTemp    MaxTemp  Rainfall  WindSpeed9am  WindSpeed3pm  \
Date                                                                     
2008-12-01  13.200000  24.083742       0.0      6.000000     19.000000   
2008-12-02  13.738447  32.200000       0.0      5.986227     19.000000   
2008-12-03  16.200000  32.200000       0.0      2.000000      2.000000   
2008-12-04  19.200000  24.000000       0.0     22.000000     22.000000   
2008-12-05  18.800000  30.200000       0.0      4.000000     10.614458   

            Humidity9am  Humidity3pm  Cloud9am  Cloud3pm    Temp9am  ...  \
Date                                                                 ...   
2008-12-01    50.000000    24.000000       3.0       4.0  21.800000  ...   
2008-12-02    74.014791    59.000000       4.0       0.0  18.101224  ...   
2008-12-03    74.000000    26.000000       4.0       4.0  22.200000  ...   
2008-12-04    66.000000    61.000000       7.0       5.0  20.400000  ...   
2008-12-05    85.000000    57.328215       8.0       4.0  20.000000  ...   

            year  month  day  LocationNum  WindDir9amNum  WindDir3pmNum  \
Date                                                                      
2008-12-01  2008     12    1            5       2.356194       2.356194   
2008-12-02  2008     12    2            5       3.068698       0.785398   
2008-12-03  2008     12    3            5       1.570796       5.497787   
2008-12-04  2008     12    4            5       5.497787       5.497787   
2008-12-05  2008     12    5            5       0.785398       4.021947   

             Latitude   Longitude  CodeRegionNum  NonMesNum  
Date                                                         
2008-12-01 -32.919295  151.779535              0          3  
2008-12-02 -32.919295  151.779535              0          3  
2008-12-03 -32.919295  151.779535              0          3  
2008-12-04 -32.919295  151.779535              0          3  
2008-12-05 -32.919295  151.779535              0          3  

[5 rows x 23 columns]

In [4]:
# Inspection de la structure de `df`

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2929 entries, 2008-12-01 to 2017-06-24
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MinTemp        2929 non-null   float64
 1   MaxTemp        2929 non-null   float64
 2   Rainfall       2929 non-null   float64
 3   WindSpeed9am   2929 non-null   float64
 4   WindSpeed3pm   2929 non-null   float64
 5   Humidity9am    2929 non-null   float64
 6   Humidity3pm    2929 non-null   float64
 7   Cloud9am       2929 non-null   float64
 8   Cloud3pm       2929 non-null   float64
 9   Temp9am        2929 non-null   float64
 10  Temp3pm        2929 non-null   float64
 11  RainToday      2929 non-null   int64  
 12  RainTomorrow   2929 non-null   int64  
 13  year           2929 non-null   int64  
 14  month          2929 non-null   int64  
 15  day            2929 non-null   int64  
 16  LocationNum    2929 non-null   int64  
 17  WindDir9amNum  2929 non-null   float64
 18

## 2. Découpage

In [5]:
# Découpage de `df` sur l'axe des colonnes : séparation des variables explicatives (`data`) et cible (`target`)

data = df.drop(columns = "RainTomorrow")
target = df["RainTomorrow"]

In [6]:
# Découpage de `data` et de `target` sur l'axe des lignes : séparation des jeux d'entraînement (`*_train`) et de test (`*_test`) avec le splitter `TimeSeriesSplit`

from sklearn.model_selection import TimeSeriesSplit

tss = TimeSeriesSplit(n_splits = 5) ## Nous fixons le paramètre `n_splits` à 5 afin d'avoir une répartition de 80 / 20 entre les jeux d'entraînement et de test, respectivement.

for train_index, test_index in tss.split(data):
    X_train, X_test = data.iloc[train_index, :], data.iloc[test_index,:]
    y_train, y_test = target.iloc[train_index], target.iloc[test_index]

## 3. Conversion

In [7]:
# Importation de la fonction artisanale `numpyfy`

from numpyfy import numpyfy

In [8]:
# Application de la fonction `numpyfy` aux 4 jeux de données issus du découpage effectué par le splitter `TimeSeriesSplit` afin de les convertir en arrays et ainsi les rendre compatibles avec `sktime`

X_train, X_test, y_train, y_test = numpyfy(X_train, X_test, y_train, y_test)

## 4. Modélisation

In [9]:
# Instanciation d'un modèle classificateur via un Pipeline

from sklearn.pipeline import Pipeline
from sktime.transformations.panel.compose import ColumnConcatenator
from sktime.classification.interval_based import TimeSeriesForestClassifier

steps = [
    ("concatenate", ColumnConcatenator()), ## Cette étape permet de transformer les jeux de données multivariées en univariées afin qu'ils puissent être traités par `TimeSeriesForestClassifier`.
    ("classify", TimeSeriesForestClassifier()),
]

clf_rf_ts = Pipeline(steps)

In [10]:
# Récupération des paramètres initiaux de la TSF

clf_rf_ts["classify"].get_params()

{'min_interval': 3, 'n_estimators': 200, 'n_jobs': 1, 'random_state': None}

In [11]:
# Entraînement du modèle

clf_rf_ts.fit(X_train, y_train)

Pipeline(steps=[('concatenate', ColumnConcatenator()),
                ('classify', TimeSeriesForestClassifier())])

In [12]:
# Récupération des paramètres ajustés de la TSF

clf_rf_ts["classify"].get_fitted_params()

{'classes': array([0, 1]),
 'intervals': [array([[ 3,  7],
         [14, 17],
         [ 2, 13],
         [12, 19]]),
  array([[ 3, 19],
         [ 0,  7],
         [16, 19],
         [17, 20]]),
  array([[ 3,  8],
         [10, 19],
         [ 0, 10],
         [12, 18]]),
  array([[ 5,  8],
         [ 7, 15],
         [12, 20],
         [11, 16]]),
  array([[ 7, 20],
         [14, 17],
         [ 5,  8],
         [ 1,  9]]),
  array([[17, 20],
         [14, 19],
         [ 5, 13],
         [ 4,  7]]),
  array([[ 3, 20],
         [ 2, 17],
         [14, 17],
         [14, 17]]),
  array([[ 5, 18],
         [ 6, 17],
         [16, 20],
         [10, 13]]),
  array([[15, 18],
         [ 4, 19],
         [ 1,  4],
         [ 4, 13]]),
  array([[ 4, 10],
         [ 9, 16],
         [16, 19],
         [17, 20]]),
  array([[14, 19],
         [10, 20],
         [17, 20],
         [13, 19]]),
  array([[ 7, 13],
         [15, 19],
         [ 6, 14],
         [ 0, 12]]),
  array([[17, 20],
     

In [13]:
# Réalisation des prédictions

y_pred = clf_rf_ts.predict(X_test)

## 5. Évaluation

In [14]:
# Élaboration de la matrice de confusion

pd.crosstab(y_test, y_pred, rownames = ["Classe réelle"], colnames = ["Classe prédite"])

Classe prédite    0   1
Classe réelle          
0               348  28
1                81  31

In [15]:
# Élaboration du rapport de classification

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86       376
           1       0.53      0.28      0.36       112

    accuracy                           0.78       488
   macro avg       0.67      0.60      0.61       488
weighted avg       0.75      0.78      0.75       488

